apiVersion: v1
kind: Secret
metadata:
  name: java-api-secret
  namespace: java-api-ns-nadun
type: Opaque
data:
  database-password: cGFzc3dvcmQxMjM= # password123
  api-key: YWJjZGVmZ2hpams= # abcdefghijk
